apiVersion: skaffold/v4beta2
kind: Config
deploy:
  helm:
    releases:
      - name: test
        chartPath: ./chart
        valuesFiles:
          - ./chart/values.yaml
        setValues:
          # svc1-app.image: svc1-app-image
          # svc2-app.image: svc2-app-image
          # rest-api.image: rest-api-image
        wait: true
build:
  local:
    push: false
  artifacts:
  - image: svc1-app-image
    context: ./svc1
    docker:
      dockerfile: docker/Dockerfile.dev
    sync: 
      manual:
        - dest: .
          src: "**/*.go"
        - dest: ./config/
          src: "config/.air.toml"
  - image: svc2-app-image
    context: ./svc2
    docker:
      dockerfile: docker/Dockerfile.dev
    sync: 
      manual:
        - dest: .
          src: "**/*.go"
        - dest: ./config/
          src: "config/.air.toml"
  - image: rest-api-image
    context: ./rest-api
    docker:
      dockerfile: docker/Dockerfile.dev
    sync: 
      manual:
        - dest: .
          src: "**/*.go"
        - dest: ./config/
          src: "config/.air.toml"
portForward:
- resourceType: deployment
  resourceName: rest-api
  port: 3000
  localPort: 3000
- resourceType: service
  resourceName: svc1-service
  port: 50050
  localPort: 50050
