{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
spec:
  selector:
    app: {{ .appName }}
  type: ClusterIP
  ports:
  - port: {{ .port }}
    targetPort: {{ .targetPort }}
    protocol: TCP
---
{{- end }}