apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1-app
  template:
    metadata:
      labels:
        app: svc1-app
    spec:
      containers:
        - name: svc1-app
          image: svc1-app-image
          ports:
            - containerPort: 50051